---
# This role installs HAProxy and configures it.

- name: update apt cache
  apt: update_cache=yes cache_valid_time=3600

- name: install haproxy
  apt: name=haproxy state=present

- name: Configure the haproxy cnf file with hosts
  template: 
    src: haproxy.cfg.j2 
    dest: /etc/haproxy/haproxy.cfg

- name: gather facts from db servers
  setup:
  delegate_to: "{{item}}"
  delegate_facts: True
  loop: "{{groups['apps']}}"
  tags:
    - dumps
  
- name: set var servers_lb
  shell: |    
    {% for host in groups.apps %}
      CPUS="{{ hostvars[host]['ansible_processor_vcpus'] }}"
      for((i = 1; i <= CPUS; i++)); do         
        echo "   server {{host}} {{ hostvars[host]['ansible_host'] }}:500${i}" >> /etc/haproxy/haproxy.cfg       
      done      
    {% endfor %}         
  args:
    executable: /bin/bash  
  tags:
    - dumps

- name: create rsyslog haproxy
  template:
    src: rsyslog-haproxy.j2
    dest: /etc/rsyslog.d/haproxy.conf
  notify:
    - restart rsyslog 

- name: Start the haproxy service
  service: name=haproxy state=started enabled=yes
