---
- import_tasks: prebootstrap.yml
  remote_user: root

- import_tasks: packages.yml
  remote_user: "{{ admin_user }}"
  become: yes

- import_tasks: set-authorized-keys-admin.yml
  remote_user: "{{ admin_user }}"
  become: yes
  tags:
    - add-remove-keys

- import_tasks: ssh-settings.yml
  remote_user: "{{ admin_user }}"
  become: yes



