---
- name: Update package cache and upgrade packages
  apt:
    upgrade: dist
    update_cache: yes
    cache_valid_time: 3600

- name: Install extra packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items: "{{ extra_packages }}"
