---
- import_playbook: prebootstrap.yml

- hosts: all
  become: yes
  roles:    
    - role: common

- hosts: apps
  become: yes
  roles:
    - role: deployconf
    - role: app
  tags:
    - apps

- hosts: lb
  become: yes
  become_user: root
  roles: 
    - role: certboot
      tags:
        - certboot
      when: certboot is defined
    - role: hproxy     
    - role: sendmail
    - role: performance
      tags:
        - performance
  tags:
    - lb  

